# Generated by Django 3.2.3 on 2023-03-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('link', models.CharField(max_length=300, verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım vaxtı')),
            ],
            options={
                'verbose_name': 'Podkast',
                'verbose_name_plural': 'Podkastlar',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Postcad',
        ),
    ]
