# Generated by Django 3.2.3 on 2023-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20230304_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Abonə',
                'verbose_name_plural': 'Abonələr',
                'ordering': ['-id'],
            },
        ),
    ]
