# Generated by Django 3.2.3 on 2023-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_remove_postcads_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('email', models.CharField(max_length=300, verbose_name='Link')),
                ('phone', models.CharField(max_length=300, verbose_name='Link')),
                ('subject', models.CharField(max_length=300, verbose_name='Link')),
                ('text', models.CharField(max_length=30000, verbose_name='Link')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım vaxtı')),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqəıər',
                'ordering': ['-id'],
            },
        ),
    ]
