# Generated by Django 3.2.3 on 2023-03-08 20:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcads',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 300], upload_to='', verbose_name='Şəkil'),
        ),
    ]
